
services:
  keycloak-db:
    image: postgres:16.1
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5543:5432"
    volumes:
      - ./infrastructure/keycloak/db:/var/lib/postgresql/data
    networks:
      - keycloak_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev # --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
#      KC_HOSTNAME_STRICT: false
#      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
      - "8080:8080"
    #    volumes:
    #      - ./infrastructure/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - keycloak-db
    networks:
      - keycloak_net

  ticket-db:
    image: postgres:16.1
    container_name: ticket_postgres
    environment:
      POSTGRES_DB: tickets
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_password
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/ticket-service/db:/var/lib/postgresql/data
    networks:
      - keycloak_net

#  api-gateway:
#    container_name: api_gateway
#    build:
#      context: ./backend/api-gateway
#      dockerfile: Dockerfile
#    ports:
#      - "8088:8080"
#    networks:
#      - keycloak_net
#    depends_on:
#      - keycloak

#  ticket-service:
#    container_name: ticket-service
#    build:
#      context: ./backend/ticket-service
#      dockerfile: Dockerfile
#    ports:
#      - "8091:8091"
#    depends_on:
#      - ticket-db
#      - keycloak
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://ticket-db:5432/tickets
#      SPRING_DATASOURCE_USERNAME: ticket_user
#      SPRING_DATASOURCE_PASSWORD: ticket_password
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/tickets
#    networks:
#      - keycloak_net

volumes:
  postgres_data:

networks:
  keycloak_net:
    driver: bridge
