server:
  port: 8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/tickets

  cloud:
    gateway:
      routes:
        - id: ticket-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/tickets/**
